version: 2.1
orbs:
  node: circleci/node@2.1
jobs:
  build-and-publish:
    executor:
      name: node/default
      tag: 'lts' 
    steps:
      - checkout
      - run: echo "registry=$SYM_NPM_READ_REPO" > ~/.npmrc
      - run: echo "_auth=$SYM_NPM_TOKEN" >> ~/.npmrc
      - run: echo "always-auth=true" >> ~/.npmrc
      - run: yarn
      - run: yarn test-once
      - run: yarn build
      - run: bash ./publish.sh
      - run: rm -f ~/.npmrc
      
workflows:
  build:
    jobs:
      - build-and-publish
          filters:
            tags:
              only: /^v.*$/