version: 2.1
orbs:
  node: circleci/node@2.1
  aws-s3: circleci/aws-s3@1.1.1
jobs:
  build-and-publish:
    executor:
      name: node/default
      tag: 'lts'
    steps:
      - checkout
      - run: echo "registry=$SYM_NPM_READ_REPO" > ~/.npmrc
      - run: echo "_auth=$SYM_NPM_TOKEN" >> ~/.npmrc
      - run: echo "always-auth=true" >> ~/.npmrc
      - run: yarn
      - run: yarn lint
      # - run: yarn test-once
      - run: yarn build
      - run: bash ./publish.sh
      - run: rm -f ~/.npmrc
      - run: rm -rf ./dist
      - run: yarn build-storybook
      - persist_to_workspace:
          root: dist
          paths:
            - storybook

  deploy-storybook:
    executor:
      name: node/default
      tag: 'lts'
    steps:
      - attach_workspace:
          at: /tmp/dist
      - aws-s3/sync:
          arguments: --delete
          from: /tmp/dist/storybook
          to: s3://uitoolkit-storybook/components/master

workflows:
  build:
    jobs:
      - build-and-publish:
          filters:
            tags:
              only: /^v.*/
      - deploy-storybook:
          requires:
            - build-and-publish
          filters:
            branches:
              only: master
